.gitlab-ci.yml
repo init required -b refs/tags/$CI_COMMIT_REF_NAME for tags
and
-b $CI_COMMIT_REF_NAME for branches
=> repo init -b variable parameter fix

payloads/external/SeaBIOS/Kconfig, payloads/external/SeaBIOS/Makefile
This PR fixes the issue: https://github.com/pcengines/seabios/issues/12#event-1369914524
=> Seabios upgrade

CHANGELOG.md
=> CHANGELOG: add info about v4.6.8

CHANGELOG.md
=> CHANGELOG: add info about v4.0.16

.gitlab-ci.yml
=> gitlab-ci.yml: use separate cache for legacy pipeline

.gitlab-ci.yml, util/crossgcc/Makefile, util/crossgcc/buildgcc
Changes required for `pce-fw-builder` support
=> Pce fw builder legacy

.gitlab-ci.yml
=> gitlab-ci.yml: use latest tag for pce-fw-builder

CHANGELOG.md
=> CHANGELOG.md: update v4.0.17 release info

CHANGELOG.md
=> CHANGELOG.md: update v4.6.9 release info

.gitlab-ci.yml
=> gitlab-ci.yml: use docker image only in build stage

.gitlab-ci.yml
=> gitlab-ci.yml: use docker image only for build stage

payloads/external/Memtest86Plus/Makefile
Change-Id: I6d20116c62522416fc67995cf53638f4277c6159
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>
=> payloads/external/Memtest86Plus: fix identation to match mainline

CHANGELOG.md
=> CHANGELOG.md: add v4.0.18 release info

CHANGELOG.md
=> CHANGELOG.md: add v4.6.10 release info

CHANGELOG.md
=> CHANGELOG.md: udpate 4.8.0.2 info

src/mainboard/pcengines/apu1/bios_knobs.c, src/mainboard/pcengines/apu1/bios_knobs.h, src/mainboard/pcengines/apu2/Kconfig, src/mainboard/pcengines/apu2/bios_knobs.c, src/mainboard/pcengines/apu2/bios_knobs.h, src/mainboard/pcengines/apu2/mainboard.c, src/mainboard/pcengines/apu2/romstage.c, src/mainboard/pcengines/apu2/s1_button.c
Signed-off-by: Adam Wawrzyński <adam.wawrzynski@3mdeb.com>
=> fix errors during test-lint

CHANGELOG.md
=> CHANGELOG.md: update v4.8.0.3 info

CHANGELOG.md
=> CHANGELOG.md: add 4.8.0.4 release info

CHANGELOG.md
=> CHANGELOG.md: add v4.8.0.5 release info

src/mainboard/pcengines/apu2/mainboard.c
=> Fix retrieving serial number

src/mainboard/pcengines/apu2/mainboard.c
=> PCIe ACS capabilities

CHANGELOG.md
=> CHANGELOG.md: add v4.8.0.7 release info

CHANGELOG.md
=> CHANGELOG.md: add v4.0.22 release info

CHANGELOG.md
=> CHANGELOG.md: fix markdown link

CHANGELOG.md
=> CHANGELOG.md: add v4.9.0.1 release info

CHANGELOG.md
=> CHANGELOG.md: add v4.0.23 release info

src/mainboard/pcengines/apu2/PlatformGnbPcie.c
=> src/mainboard/pcengines/apu2/PlatformGnbPcie.c: enable CPB

CHANGELOG.md
=> CHANGELOG.md: add v4.9.0.2 release info

.gitlab-ci.yml
=> .gitlab-ci.yml: upgrade coreboot SDK to 1.52

src/arch/x86/smbios.c, src/include/smbios.h, src/mainboard/pcengines/apu2/mainboard.c
=> add ECC info

.gitlab-ci.yml
=> .gitlab-ci.yml: add autimatic generation and upload of SHA256 sums

src/mainboard/pcengines/apu2/acpi/superio.asl, src/mainboard/pcengines/apu2/dsdt.asl
=> src/mainboard/pcengines/apu2/acpi/superio.asl: describe serial ports

.gitlab-ci.yml
=> .gitlab-ci.yml: fix generation of SHA256 files and their extensions

CHANGELOG.md
=> CHANGELOG.md: update file to release v4.10.0.1

CHANGELOG.md
=> CHANGELOG.md: update file to release v4.0.28

payloads/external/tianocore/Kconfig, payloads/external/tianocore/Makefile, src/arch/x86/Makefile.inc, src/drivers/uart/uart8250io.c, src/mainboard/pcengines/apu1/Makefile.inc
=> fix tianocore and apu1 build

src/superio/nuvoton/nct5104d/nct5104d.h, src/superio/nuvoton/nct5104d/superio.c
=> [Legacy] GPIO soft reset to default state: IN, OD

src/mainboard/pcengines/apu2/mainboard.c, src/southbridge/amd/pi/hudson/sd.c
=> legacy sd 3.0 mode enable/disable

src/mainboard/pcengines/apu2/acpi/buttons.asl, src/mainboard/pcengines/apu2/acpi/gpio.asl, src/mainboard/pcengines/apu2/acpi/leds.asl, src/mainboard/pcengines/apu2/dsdt.asl, src/mainboard/pcengines/apu2/variants/apu2/devicetree.cb, src/mainboard/pcengines/apu2/variants/apu3/devicetree.cb, src/mainboard/pcengines/apu2/variants/apu4/devicetree.cb, src/mainboard/pcengines/apu2/variants/apu5/devicetree.cb, src/southbridge/amd/pi/hudson/acpi/fch.asl, src/superio/nuvoton/nct5104d/chip.h, src/superio/nuvoton/nct5104d/superio.c
=> Add GPIO ACPI and GPIO superIO support

CHANGELOG.md
=> [legacy] CHANGELOG.md: update file to release v4.0.29

CHANGELOG.md
=> CHANGELOG.md: update file to release v4.10.0.2

src/mainboard/pcengines/apu2/bootblock.c, src/mainboard/pcengines/apu2/romstage.c
=> src/mainboard/pcengines/apu2/romstage.c: send commands to the LPC MCU

.gitmodules, payloads/external/GRUB2/Kconfig, payloads/external/GRUB2/Makefile, src/arch/x86/include/arch/acpi.h, src/northbridge/amd/pi/00730F01/northbridge.c
=> nb/amd/pi/00730F01/northbridge: refactor IVRS

CHANGELOG.md
Signed-off-by: Piotr Kleinschmidt <piotr.kleinschmidt@3mdeb.com>
=> Legacy release v4.0.30 - update CHANGELOG.md

src/mainboard/pcengines/apu2/mainboard.c, src/southbridge/amd/pi/hudson/sd.c
=> src/southbridge/amd/pi/hudson/sd.c: move SD 3.0 check to southbridge

src/mainboard/pcengines/apu2/variants/apu5/devicetree.cb
Signed-off-by: Marek Kasiewicz <marek.kasiewicz@3mdeb.com>
=> Turned on GPIO1 in devicetree.cb

CHANGELOG.md
=> CHANGELOG.md: add v4.0.31 release info

src/mainboard/pcengines/apu1/mainboard.c
Signed-off-by: Piotr Kleinschmidt <piotr.kleinschmidt@3mdeb.com>
=> Fix apu1 serial number counting from MAC address

CHANGELOG.md, payloads/external/sortbootorder/Makefile.inc
=> WIP: release 4.0.32

.gitlab-ci.yml, .gitlab-ci/regression.sh
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
=> .gitlab-ci.yml: trigger regression tests

.gitlab-ci.yml
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
=> gitlab-ci.yml: use local gitlab runner for regression tests

.gitlab-ci.yml
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
=> gitlab-ci.yml: increase regression job timeout

.gitlab-ci.yml, .gitlab-ci/check_hw_matrix.sh, .gitlab-ci/regression.sh
Signed-off-by: Damian Karaś <damian.karas@3mdeb.com>
=> .gitlab-ci: add checking hw matrix job before regression

.gitlab-ci/check_hw_matrix.sh
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>
Change-Id: I3af5d67fc85cd419dd63b3aabeae75e71a23ee32
=> .gitlab-ci/check_hw_matrix.sh: fix submodule path

.gitlab-ci/check_hw_matrix.sh
Signed-off-by: Przemyslaw Sulewski <przemyslaw.sulewski@3mdeb.com>
=> Hw matrix script add fw parameter

.gitlab-ci.yml
Signed-off-by: Przemysław Sulewski <przemyslaw.sulewski@3mdeb.com>
=> Gitlab ci add apu7
