payloads/Kconfig, payloads/external/Makefile.inc, payloads/external/Memtest86Plus/Makefile, src/mainboard/pcengines/apu2/Kconfig
All changes related to CB_NOSPD are reverted. Memtest86+ switched to mainline. Stable revision hash points to "spd: fix SMBus hang for AMD ML_A0 and ML_A1 stepping" which fixes the problem with SPD.
Memtest does not hang now.
=> Memtest86+: revert CB_NOPSD changes and switch to mainline

.gitignore, Makefile.inc, payloads/external/SeaBIOS/Kconfig, payloads/external/iPXE/Kconfig, payloads/external/iPXE/Makefile.inc, src/Kconfig, src/device/Kconfig, src/mainboard/pcengines/apu2/Makefile.inc, src/mainboard/pcengines/apu3/Makefile.inc, src/mainboard/pcengines/apu5/Makefile.inc
Manually tested with SeaBIOS 1.11.0.1. No build errors or warnings.
=> Update ipxe legacy

src/southbridge/amd/pi/hudson/sd.c
`0xA8` register should also be properly initialized in SD 2.0 mode (present in legacy).
=> disable SDR50 tuning in SD 2.0 mode

payloads/external/iPXE/Kconfig
Change-Id: Ibe7a68d13dadf69d8b4218f2db5f052474489818
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>
=> payloads/external/iPXE: fix iXPE general.h and bootmenu path

src/mainboard/pcengines/apu1/mainboard.c, src/mainboard/pcengines/apu2/mainboard.c
=> pcengines/apu{1,2}: fix BIOS Release Date format in SMBIOS

src/northbridge/amd/pi/agesawrapper.c
If HOP_COUNT_TABLE doesn't exist AmdInitLate() returns error when
creating CDIT, which scaries users. This patch checks if mentioned
table exists and turns off CDIT generation when it doesn't.
After this patch AGESA_UNSUPPORTED is returned due to a bug in
AGESA which cannot be walked around without disabling DMI table
generation (`AGESA_STATUS Status = TRUE`, present in open source
version of AGESA too).
=> agesawrapper.c: check if HOP_COUNT_TABLE exists before AmdInitLate()

src/mainboard/pcengines/apu2/BiosCallOuts.c
=> BiosCallOuts.c: don't enable EHCI0 in AGESA for apu2 even if requested

src/mainboard/pcengines/apu2/mainboard.c
Memtest pro logs from APU2/3/4/5:
[apu2.log](https://github.com/pcengines/coreboot/files/2727234/apu2.log)
[apu3.log](https://github.com/pcengines/coreboot/files/2727235/apu3.log)
[apu4.log](https://github.com/pcengines/coreboot/files/2727236/apu4.log)
[apu5.log](https://github.com/pcengines/coreboot/files/2727237/apu5.log)
=> src/mainboard/pcengines/apu2/mainboard.c : enabled ECC

src/mainboard/pcengines/apu1/romstage.c
=> src/mainboard/pcengines/apu1/romstage.c: add missing includes

src/mainboard/pcengines/apu2/romstage.c
ColdRstDet in D18F0x6C can be switched from OS with
* `setpci -s 18.0 6c.L=10:10` (Linux)
* `pciconf -w pci0:24:0 0x6c 0x580ffe10` (FreeBSD)
=> pcengines/apu2/romstage.c: force cold boot if ColdRstDet=1

src/mainboard/pcengines/apu2/romstage.c
SVI wait completion message is now unvisible in sign-of-life
=> Fixing sign-of-life message SVI2

src/mainboard/pcengines/apu2/romstage.c
Fix MMIO access and remove incorrect clock request mapping. Leave clocks to be always on for the time now.
=> src/mainboard/pcengines/apu2/romstage.c: fix MMIO access

CHANGELOG.md
=> Release coreboot legacy v4.0.28

src/cpu/amd/agesa/family14/acpi/cpu.asl, src/cpu/amd/agesa/family15tn/acpi/cpu.asl, src/cpu/amd/agesa/family16kb/acpi/cpu.asl, src/cpu/amd/pi/00630F01/acpi/cpu.asl, src/cpu/amd/pi/00660F01/acpi/cpu.asl, src/cpu/amd/pi/00730F01/acpi/cpu.asl
This reverts commit 2c34892efd0aa2dd4491db81e63c9596502753b3.
=> Revert "cpu/amd/*/*/acpi/: Use 'Device()' instead of 'Processor()'"

src/mainboard/pcengines/apu2/OemCustomize.c, src/mainboard/pcengines/apu2/romstage.c
Platform hanged without setting RstToCpuPwrGdEn.
Code for enabling watchdog is now in board_BeforeInitEarly, as hardware
is not enabled before InitReset. It didn't work on first boot after
power cycle.
=> Watchdog fixes

src/northbridge/amd/agesa/family14/northbridge.c
Signed-off-by: Marek Kasiewicz <marek.kasiewicz@3mdeb.com>
=> family14/northbridge.c: remove patching ssdt processor scope

.gitmodules
=> gitmodules: use absolute URL for qc_blobs

util/cbmem/cbmem.c
Strings in vendor info and event data do not have to be null-terminated.
Before this patch, PCR number (which was non-printable ASCII)  was printed
at the end of the line. Now, this is truncated to the length specified by
the event structure.
In fact, those fields do not have to be strings at all. Binary data is
printed to the first zero byte, which in most cases is the first byte.
There is no easy and efficient way to test whether it is binary or text.
=> util/cbmem: fix printing strings from DRTM event log

src/mainboard/pcengines/apu2/acpi/buttons.asl, src/mainboard/pcengines/apu2/acpi/leds.asl, src/mainboard/pcengines/apu2/dsdt.asl
This restores the ACPI GPIO bindings on apu2-6 devices. This restores the previous method of accessing the GPIOs used and should be used instead of the Linux `pcengines-apuv2` driver, which as of today in the mainline kernel, does not correctly support the S1 button.
See comment https://github.com/pcengines/apu2-documentation/issues/204#issuecomment-957314690
This reverts commit bca61d7cc6986d1b1158a45b3513b8af30edf77c.
=> Revert "mb/pcengines/apu2: Remove ACPI GPIO bindings"

src/northbridge/amd/pi/00730F01/northbridge.c
=> src/northbridge/amd/pi/00730F01/northbridge.c: enable PSP MMIO BARs

src/mainboard/pcengines/apu1/romstage.c, src/mainboard/pcengines/apu2/romstage.c
The coreboot build date shown by `print_sign_of_life` at early boot was incorrectly presented in `yyyyddmm` format, when it should have been `yyyymmdd`.
For example, the [current version, 4.16.0.4](https://pcengines.github.io/#mr-59), was built on 2022-05-25 and released on 2022-05-26. It boots with the following sign-of-life message:
```
PC Engines apu2
coreboot build 20222505
BIOS version v4.16.0.4
```
`yyyyddmm` is not a date format that any ordinary person would expect or understand. It presents as a standard `yyyymmdd` date seemingly referring to the 5th day of the 25th month of 2022, which of course is incorrect. The string should be presented as `coreboot build 20220525`, in proper `yyyymmdd` format.
There’s a bit of history to this string, and I wanted to make sure that this …
=> mainboard/pcengines: fix sign-of-life coreboot build date
